version: "3.9"

services:
  file-classifier:
    build: .
    container_name: file-classifier
    restart: unless-stopped
    volumes:
      # 宿主机下载目录挂载到容器内 /data
      - ~/Downloads:/data:rw
      # 日志输出目录
      - ./logs:/app/logs:rw
    environment:
      - NODE_ENV=production
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o-mini
      - ROOT_DIR=/data/分类库
      - INCOMING_DIR=/data/待分类
      - CRON_SCHEDULE=0 * * * *
      - LOG_LEVEL=info
      - LOG_FILE=/app/logs/move.log
      - SIMILARITY_THRESHOLD=0.65
      - MAX_SCAN_DEPTH=3
    working_dir: /app
