version: "3.9"

services:
  file-classifier:
    image: docker.io/zkl2333/file-auto-organizer:latest
    container_name: file-classifier
    restart: unless-stopped
    volumes:
      # 宿主机下载目录挂载到容器内 /data
      - ~/Downloads:/data:rw
      # 日志输出目录
      - ./logs:/app/logs:rw
      # 配置文件挂载
      - ./config.yaml:/app/config.yaml:ro
    working_dir: /app
